apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rl-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rl-cluster
  source:
    repoURL: https://github.com/RobertLemmens/rl-cluster.git
    targetRevision: HEAD
    path: cluster-root
  destination:
    server: https://kubernetes.default.svc
    namespace: rl-cluster
  syncPolicy:
    automated:
      selfheal: true
      prune: true
      allowEmpty: true
