apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-contour
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rl-cluster
  source:
    chart: contour
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: projectcontour
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
