{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - minio.codebulb.nl
    secretName: minio-tls
  rules:
    - host: "minio.codebulb.nl"
      http:
        paths:
          - path: "/"
            backend:
              serviceName: minio
              servicePort: "443"

