apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: kube-prometheus
  resources:
    requests:
      memory: 300Mi
  enableAdminAPI: true