apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rl-cluster
  source:
    path: cluster-applications/docker-registry
    repoURL: https://github.com/RobertLemmens/rl-cluster.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: rl-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
