---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: controller
  name: controller
  namespace: rl-cluster
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative
  selector:
    matchLabels:
      app: controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: autoscaler
  name: autoscaler
  namespace: rl-cluster
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative
  selector:
    matchLabels:
      app: autoscaler
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: activator
  name: activator
  namespace: rl-cluster
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative
  selector:
    matchLabels:
      app: activator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: webhook
  name: webhook
  namespace: rl-cluster
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative
  selector:
    matchLabels:
      app: webhook
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: broker-filter
  name: broker-filter
  namespace: rl-cluster
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative
  selector:
    matchLabels:
      eventing.knative.dev/brokerRole: filter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: broker-ingress
  name: broker-ingress
  namespace: rl-cluster
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative
  selector:
    matchLabels:
      eventing.knative.dev/brokerRole: ingress
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: eventing-controller
  labels:
    app: eventing-controller
  namespace: rl-cluster
spec:
  selector:
    matchLabels:
      app: eventing-controller
  namespaceSelector:
    matchNames:
    - knative
  podMetricsEndpoints:
  - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: imc-controller
  namespace: rl-cluster
spec:
  selector:
    matchLabels:
      messaging.knative.dev/role: controller
  namespaceSelector:
    matchNames:
    - knative
  podMetricsEndpoints:
  - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ping-source
  namespace: rl-cluster
spec:
  selector:
    matchLabels:
      eventing.knative.dev/source: ping-source-controller
  namespaceSelector:
    matchNames:
    - knative
  podMetricsEndpoints:
  - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: apiserver-source
  namespace: rl-cluster
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
     eventing.knative.dev/source: apiserver-source-controller
  podMetricsEndpoints:
  - port: metrics
