apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rl-cluster
  source:
    path: charts/ingress-nginx
    repoURL: https://github.com/kubernetes/ingress-nginx.git
    targetRevision: HEAD
    helm:
      parameters:
      - name: controller.metrics.enabled
        value: "true"
      - name: controller.metrics.serviceMonitor.enabled
        value: "true"
      - name: controller.metrics.serviceMonitor.additionalLabels.release
        value: "prometheus"
      - name: controller.metrics.serviceMonitor.namespace
        value: "rl-cluster"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
