apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rl-cluster
  source:
    path: cluster-applications/knative
    repoURL: https://github.com/RobertLemmens/rl-cluster.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: knative
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
      allowEmpty: true

