apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rl-cluster
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 42.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: rl-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
